FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements-dev.txt ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
