# Generated by Django 5.2.10 on 2026-01-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('short_pitch', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'StartupProfile',
            },
        ),
    ]
