# Generated by Django 5.2.10 on 2026-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_region_startupprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='startups', to='startups.region'),
        ),
    ]
