# Generated by Django 5.2.10 on 2026-02-04 16:28

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0004_alter_startupprofile_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="startupprofile",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["uuid"], name="startup_pro_uuid_79de9f_idx"),
        ),
    ]
