# Generated by Django 5.2.10 on 2026-02-04 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0005_startupprofile_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupprofile",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
