# Generated by Django 5.2.10 on 2026-02-04 16:29

import uuid
from django.db import migrations, models
from django.db.models import Count


def dedupe_startup_profile_uuids(apps, schema_editor):
    StartupProfile = apps.get_model("startups", "StartupProfile")

    # Backfill any NULLs just in case.
    for sp in StartupProfile.objects.filter(uuid__isnull=True).only("id"):
        sp.uuid = uuid.uuid4()
        sp.save(update_fields=["uuid"])

    # If the UUID field was added as NOT NULL with a default, Django may have
    # backfilled existing rows with the same value. Make them unique before we
    # enforce a UNIQUE constraint.
    duplicates = (
        StartupProfile.objects.values("uuid")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )

    for row in duplicates:
        dup_uuid = row["uuid"]
        ids = list(
            StartupProfile.objects.filter(uuid=dup_uuid)
            .order_by("id")
            .values_list("id", flat=True)
        )
        # Keep the first record as-is, fix the rest.
        for sp_id in ids[1:]:
            StartupProfile.objects.filter(id=sp_id).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0005_startupprofile_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_startup_profile_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="startupprofile",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
