# Generated by Django 5.2.10 on 2026-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0007_startupprofile_pitch_deck_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupprofile",
            name="pitch_deck_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
