# Generated by Django 5.2.10 on 2026-01-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startup_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='Projects_title_ea837e_idx'),
        ),
    ]
