# Generated by Django 5.2.10 on 2026-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
