# Generated by Django 5.2.10 on 2026-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.region'),
        ),
    ]
