# Generated by Django 5.2.10 on 2026-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
