# Generated by Django 5.2.10 on 2026-02-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_allow_overfunding_project_funded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModerationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("pending_count", models.IntegerField(default=0)),
                ("approved_count", models.IntegerField(default=0)),
                ("rejected_count", models.IntegerField(default=0)),
                ("flagged_count", models.IntegerField(default=0)),
                ("deleted_count", models.IntegerField(default=0)),
                ("restored_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Project moderation statistics",
                "db_table": "project_moderation_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When project was soft-deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who deleted the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, help_text="When project was last moderated", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who performed last moderation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderation_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for moderators"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                default="pending",
                help_text="Current moderation status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection (sent to startup owner)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Soft delete flag"
            ),
        ),
        migrations.CreateModel(
            name="ProjectModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("flag", "Flag"),
                            ("restore", "Restore"),
                            ("delete", "Soft Delete"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the action"),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous moderation status",
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="New moderation status", max_length=20
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (IP, user agent, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        help_text="Admin who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_moderation_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_mod_project_04328b_idx",
                    ),
                    models.Index(
                        fields=["moderator", "created_at"],
                        name="project_mod_moderat_8a4747_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="project_mod_action_5e41d2_idx",
                    ),
                ],
            },
        ),
    ]
