# Generated by Django 5.2.10 on 2026-02-10 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_allow_overfunding_project_funded_at_and_more'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='upload',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uploads.upload'),
        ),
    ]
