# Generated by Django 5.2.10 on 2026-02-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='moderation_status',
        ),
    ]
