# Generated by Django 5.2.10 on 2026-02-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_deleted_at_project_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectaudit",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="projectaudit",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="projectaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("revert", "Revert"),
                ],
                default="create",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectaudit",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="projects.project",
            ),
        ),
    ]
