# Generated by Django 5.2.10 on 2026-02-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectattachment_upload'),
        ('projects', '0005_projectmoderationstats_project_deleted_at_and_more'),
    ]

    operations = [
    ]
