# Generated by Django 5.2.10 on 2026-02-18 20:42

from django.db import migrations


def delete_orphan_uploads(apps, schema_editor):
    Upload = apps.get_model("uploads", "Upload")
    Upload.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0002_upload_user"),
    ]

    operations = [
        migrations.RunPython(delete_orphan_uploads, reverse_code=migrations.RunPython.noop),
    ]