# Generated by Django 5.2.10 on 2026-02-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_upload_user_not_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
