# Generated by Django 5.2.10 on 2026-01-13 18:16

from django.db import migrations, models

import startup_gateway.content.models as content_models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero", models.JSONField(default=content_models.default_hero)),
                ("for_whom", models.JSONField(default=content_models.default_for_whom)),
                (
                    "why_worth",
                    models.JSONField(default=content_models.default_why_worth),
                ),
                (
                    "footer_links",
                    models.JSONField(default=content_models.default_footer_links),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
