# Generated by Django 5.2.10 on 2026-02-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='investors.investorprofile')),
            ],
            options={
                'db_table': 'saved_items',
            },
        ),
        migrations.DeleteModel(
            name='SavedStartup',
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['content_type', 'object_id'], name='saved_items_content_fa3bca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('investor_profile', 'content_type', 'object_id')},
        ),
    ]
