# Generated by Django 5.2.10 on 2026-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboard", "0002_saveditem_delete_savedstartup_and_more"),
        ("investors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveditem",
            name="object_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="saveditem",
            index=models.Index(
                fields=["investor_profile", "content_type"],
                name="saved_items_investo_13f5a5_idx",
            ),
        ),
    ]
