# Generated by Django 5.2.10 on 2026-01-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstartap',
            name='startap_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_investors', to='startups.startupprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='savedstartap',
            unique_together={('investor_profile', 'startap_profile')},
        ),
    ]
