# Generated by Django 5.2.10 on 2026-02-10 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_project_event_key"),
        ("projects", "0004_project_allow_overfunding_project_funded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_e78525_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_3f8c44_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_key",
            field=models.CharField(default="unknown", max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_7336fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["project"], name="notificatio_project_4e14ab_idx"
            ),
        ),
    ]
