# Generated by Django 5.2.10 on 2026-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
