# Generated by Django 6.0.1 on 2026-01-24 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address used in request', max_length=254)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of requester')),
                ('token_sent', models.BooleanField(default=False, help_text='Whether reset token was actually sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who requested reset (null if email not found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_password_reset_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='users_passw_email_84c13c_idx'), models.Index(fields=['ip_address', 'created_at'], name='users_passw_ip_addr_81d892_idx')],
            },
        ),
    ]
