# Generated by Django 5.2.10 on 2026-01-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumbnail_url'),
        ('users', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='media_urls',
            field=models.FileField(blank=True, upload_to='user/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_tags',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserTag', to='projects.tag'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['user'], name='users_tags_user_id_64d05a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['tag'], name='users_tags_tag_id_f118ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag')},
        ),
    ]
