# Generated by Django 5.2.10 on 2026-01-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetattempt'),
        ('users', '0003_user_email_verification_nonce'),
    ]

    operations = [
    ]
