# Generated by Django 5.2.10 on 2026-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_passwordresetconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_version",
            field=models.IntegerField(
                default=0,
                help_text="Incremented on password change to invalidate existing JWT tokens",
            ),
        ),
    ]
