# Generated by Django 5.2.10 on 2026-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_about_html_user_contact_user_media_urls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
