# Generated by Django 5.2.10 on 2026-02-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_jwt_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetconfirmation",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid_uid", "Invalid UID"),
                    ("invalid_token", "Invalid Token"),
                    ("token_expired", "Token Expired"),
                    ("weak_password", "Weak Password"),
                    ("validation_error", "Validation Error"),
                ],
                help_text="Reason for failure if success=False (e.g., 'invalid_token', 'token_expired', 'weak_password')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="ip_address",
            field=models.GenericIPAddressField(
                help_text="IP address where password reset was attempted"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_confirmations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetconfirmation",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="users_passw_ip_addr_16dd24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetconfirmation",
            index=models.Index(
                fields=["success", "created_at"], name="users_passw_success_a70ee9_idx"
            ),
        ),
    ]
