# Generated by Django 5.2.10 on 2026-02-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_passwordresetconfirmation_failure_reason_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="passwordresetconfirmation",
            name="users_passw_ip_addr_16dd24_idx",
        ),
        migrations.RemoveIndex(
            model_name="passwordresetconfirmation",
            name="users_passw_success_a70ee9_idx",
        ),
        migrations.RemoveField(
            model_name="passwordresetconfirmation",
            name="failure_reason",
        ),
        migrations.RemoveField(
            model_name="user",
            name="jwt_version",
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="ip_address",
            field=models.GenericIPAddressField(
                help_text="IP address where password was reset"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_confirmations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
