# Generated by Django 5.2.10 on 2026-02-05 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0008_remove_passwordresetconfirmation_users_passw_ip_addr_16dd24_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetconfirmation",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid_uid_format", "Invalid UID Format"),
                    ("invalid_uid_or_user", "Invalid UID or User Not Found"),
                    ("invalid_token", "Invalid or Expired Token"),
                    ("weak_password", "Weak Password"),
                    ("validation_error", "Other Validation Error"),
                ],
                help_text="Internal categorization of failure (not exposed to users)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jwt_version",
            field=models.IntegerField(
                default=0,
                help_text="Incremented on password change to invalidate existing JWT tokens",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="ip_address",
            field=models.GenericIPAddressField(
                help_text="IP address where password reset was attempted"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetconfirmation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_confirmations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetconfirmation",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="users_passw_ip_addr_16dd24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetconfirmation",
            index=models.Index(
                fields=["success", "created_at"], name="users_passw_success_a70ee9_idx"
            ),
        ),
    ]
