# Generated by Django 5.2.10 on 2026-02-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_uuid"),
        ("users", "0009_passwordresetconfirmation_failure_reason_and_more"),
    ]

    operations = []
