# Generated by Django 5.2.10 on 2026-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_merge_20260210_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetconfirmation",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User-Agent header", null=True
            ),
        ),
    ]
